### ISSUE TITLE
Received an error while trying to fetch the pool state

### ISSUE THREAD

**Issue by ubani** [KYVENetwork/core#20]
Failing to create a validator node   

```
Received an error while trying to fetch the pool state:  
 Error  missing revert data in call exception (error={"stack":"Error: processing response error (body=\"  
{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"error\\\":{\\\"code\\\":-32603,\\\"message\\\":\\\"VM Exception while processing transaction:   
revert\\\",\\\"data\\\":\\\"\\\"},\\\"id\\\":43}\\n\", error={\"stack\":\"Error: VM Exception while processing transaction: revert\\n    
  at getResult (/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)\\n    
  at processJsonFunc (/node_modules/@ethersproject/web/lib/index.js:309:22)\\n   
   at /node_modules/@ethersproject/web/lib/index.js:241:46\\n   
   at step (/node_modules/@ethersproject/web/lib/index.js:33:23)\\n  
    at Object.next (/node_modules/@ethersproject/web/lib/index.js:14:53)\\n   
   at fulfilled (/node_modules/@ethersproject/web/lib/index.js:5:58)\\n   
   at processTicksAndRejections (internal/process/task_queues.js:95:5)\",\"message\":  
  \"VM Exception while processing transaction: revert\",\"code\":-32603,\"data\":\"\"}, requestBody=\"{\\\"method\\\":\\\"eth_call\\\",\\\"params\\\":[{\\\"from\\\":
...

      at Logger.makeError (/node_modules/@ethersproject/logger/lib/index.js:199:21)
      at Logger.throwError (/node_modules/@ethersproject/logger/lib/index.js:208:20)
      at /node_modules/@ethersproject/web/lib/index.js:266:32
      at step (/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","error":{"code":-32603,"message":"VM Exception while processing transaction: revert","data":""},"id":43}\n',
    error: Error: VM Exception while processing transaction: revert
        at getResult (/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)
        at processJsonFunc (/node_modules/@ethersproject/web/lib/index.js:309:22)
        at /node_modules/@ethersproject/web/lib/index.js:241:46
        at step (/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (internal/process/task_queues.js:95:5) {
      code: -32603,
      data: ''

```

**Comment by fabianriewe** [comment]
Transferring the issue to: https://github.com/KYVENetwork/core/issues

**Comment by fabianriewe** [comment]
This looks like you might have an incorrect pool id. We will have a look and should add some try catch block to prevent this from happening again.

**Comment by ubani** [comment]
I've been using the ids given on the staking website
